FROM python:3.11-slim
WORKDIR /app
COPY requirements.frontend.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py .
CMD streamlit run app.py \
    --server.address=0.0.0.0 \
    --server.port=${PORT:-8080} \
    --server.headless=true \
    --server.enableCORS=false \
    --server.enableXsrfProtection=false
