FROM python:3.11-slim
WORKDIR /app

COPY requirements.backend.txt ./requirements.backend.txt
RUN pip install --no-cache-dir -r requirements.backend.txt

COPY . .

EXPOSE 8080

# Arranca única y exclusivamente FastAPI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
